services:
  database:
    build: ./database
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    depends_on:
      - database
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@database:5432/blogdb
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    working_dir: /api

  react-app:
    build: ./web/app
    # no se publica, solo se usa para construir
    volumes:
      - react-build:/app/dist
    depends_on:
      - api
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - api
      - react-app
    volumes:
      - react-build:/usr/share/nginx/html:ro
volumes:
  pgdata:
  react-build:
